import os
import re
import logging
from docx import Document
from fpdf import FPDF
from core.models import QuestionPaperBlueprint
from core.config import settings

class Exporter:
    @staticmethod
    def _get_paths(doc_id: str):
        base = os.path.join(settings.EXPORT_DIR, doc_id)
        return f"{base}_qpaper.docx", f"{base}_answerkey.docx", f"{base}_qpaper.pdf"

    @staticmethod
    def _clean_text_for_pdf(text: str) -> str:
        """Sanitizes AI text so the strict FPDF2 engine doesn't crash."""
        if not text:
            return ""
            
        # 1. Replace smart quotes/dashes generated by the LLM
        text = text.replace('“', '"').replace('”', '"').replace('‘', "'").replace('’', "'")
        text = text.replace('–', '-').replace('—', '-')
        
        # 2. Prevent FPDF crash by shrinking huge continuous symbols
        text = re.sub(r'_{10,}', '__________', text)
        text = re.sub(r'-{10,}', '----------', text)
        text = re.sub(r'\.{10,}', '..........', text)
        
        # 3. THE MAGIC FIX: If a word/string has no spaces for 60 characters (like a huge URL), 
        # FPDF will crash. We inject a space forcefully so it can wrap to the next line.
        text = re.sub(r'(\S{60})', r'\1 ', text)
        
        # 4. Ignore unsupported unicode characters instead of replacing with '?'
        return text.encode('latin-1', 'ignore').decode('latin-1')

    @staticmethod
    def to_docx(blueprint: QuestionPaperBlueprint, doc_id: str):
        qp_path, ak_path, _ = Exporter._get_paths(doc_id)
        
        # --- Question Paper ---
        doc_qp = Document()
        doc_qp.add_heading(blueprint.title, 0)
        doc_qp.add_paragraph(f"Language: {blueprint.language} | Max Marks: {sum([q.marks for s in blueprint.sections for q in s.questions])}")
        
        for sec in blueprint.sections:
            doc_qp.add_heading(sec.name, level=1)
            for q in sec.questions:
                q_text = q.text.replace(" / ", "\n")
                doc_qp.add_paragraph(f"Q{q.q_number}. {q_text} ({q.marks} Marks) [{q.difficulty}]")
                if q.options:
                    for opt in q.options:
                        opt_text = opt.text.replace(" / ", "\n   ")
                        doc_qp.add_paragraph(f"   {opt.label}) {opt_text}")
        doc_qp.save(qp_path)

        # --- Answer Key ---
        doc_ak = Document()
        doc_ak.add_heading(f"{blueprint.title} - Answer Key & Explanations", 0)
        for sec in blueprint.sections:
            doc_ak.add_heading(sec.name, level=1)
            for q in sec.questions:
                p = doc_ak.add_paragraph()
                p.add_run(f"Q{q.q_number}: ").bold = True
                ans_text = q.answer.replace(" / ", "\n")
                p.add_run(f"{ans_text}\n")
                p.add_run(f"Explanation:\n").italic = True
                exp_text = q.explanation.replace(" / ", "\n")
                p.add_run(f"{exp_text}\n")
                p.add_run(f"Bloom's Taxonomy: {q.blooms_taxonomy}") 
        doc_ak.save(ak_path)

        return qp_path, ak_path

    @staticmethod
    def to_pdf(blueprint: QuestionPaperBlueprint, doc_id: str):
        _, _, pdf_path = Exporter._get_paths(doc_id)
        
        try:
            pdf = FPDF()
            # FIX: Explicitly tell FPDF to create new pages automatically when text reaches the bottom margin
            pdf.set_auto_page_break(auto=True, margin=15)
            pdf.add_page()
            
            # TITLE
            pdf.set_font("Arial", 'B', 16)
            # FIX: Changed from cell() to multi_cell() so long titles wrap properly instead of shooting off-page
            pdf.multi_cell(0, 10, txt=Exporter._clean_text_for_pdf(blueprint.title), align='C')
            
            pdf.set_font("Arial", size=12)
            
            # SECTIONS & QUESTIONS
            for sec in blueprint.sections:
                pdf.ln(8) # Line break 
                pdf.set_font("Arial", 'B', 14)
                pdf.multi_cell(0, 10, txt=Exporter._clean_text_for_pdf(sec.name))
                pdf.set_font("Arial", size=12)
                
                for q in sec.questions:
                    pdf.ln(4) # Small gap between questions
                    q_text_fmt = q.text.replace(" / ", "\n")
                    q_text = f"Q{q.q_number}. {q_text_fmt} ({q.marks} Marks)"
                    pdf.multi_cell(0, 8, txt=Exporter._clean_text_for_pdf(q_text))
                    
                    if q.options:
                        for opt in q.options:
                            opt_text_fmt = opt.text.replace(" / ", "\n   ")
                            opt_text = f"   {opt.label}) {opt_text_fmt}"
                            pdf.multi_cell(0, 6, txt=Exporter._clean_text_for_pdf(opt_text))
                            
            pdf.output(pdf_path)
            return pdf_path
            
        except Exception as e:
            # SAFETY NET: If PDF fails for any bizarre layout reason, don't crash the server.
            # The DOCX files will still be successfully created and served to the user!
            logging.error(f"FPDF generation failed, but DOCX succeeded. Error: {str(e)}")
            return None